apiVersion : apps/v1
kind: Deployment
metadata:
  name: "mispk8-2e1a"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "mispk8-2e1a"
  template:
    metadata:
      labels:
        app: "mispk8-2e1a"
    spec:
      containers:
        - name: "mispk8-2e1a"
          image: "mighty.azurecr.io/mispk8"
          ports:
          - containerPort: 80