on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: mighty.azurecr.io
        username: ${{ secrets.acr_mighty_username }}
        password: ${{ secrets.acr_mighty_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/container" -f  "container/Dockerfile" -t mighty.azurecr.io/mispk8:${{ github.sha }}
        docker push mighty.azurecr.io/mispk8:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_mispk8_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep threatintel | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace threatintel`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: threatintel
        container-registry-url: mighty.azurecr.io
        container-registry-username: ${{ secrets.acr_mighty_username }}
        container-registry-password: ${{ secrets.acr_mighty_password }}
        secret-name: mispk8dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: threatintel
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          mighty.azurecr.io/mispk8:${{ github.sha }}
        imagepullsecrets: |
          mispk8dockerauth